stravalib/stravalib

- stravalib/client.py
- stravalib/tests/functional/test_client.py
Adds http://strava.github.io/api/v3/activities/#get-related functionality
(Changelog Dec 29th 2014 entry)
> Adding get related activites functionality to client

- stravalib/client.py
dlenski@772eb42 : The name of the activity should be in parameter `name`, not `activity_name`, and a `description` can be included too. (http://strava.github.io/api/v3/uploads/#post-file)
dlenski@70025d6 : The `upload_activity` response may not contain an `id` field if the response is `401 Unauthorized`
> fixes for upload_activity

- setup.py
Removed beautifulsoup4 from install_requires in setup.py as it is not used by stravalib.
> removed beautifulsoup4 install requirement

- stravalib/client.py
I added the ability change the number of context entries when requesting a segment leaderboard, documented here: http://strava.github.io/api/v3/segments/#leaderboard
> added context_entries parameter to get_segment_leaderboard method

- stravalib/model.py
New-style string formatting [doesn't play nice](http://www.voidspace.org.uk/python/weblog/arch_d7_2010_04_10.shtml) when mixing encodings. Use `__unicode__` rather than `__repr__` and ensure everything is unicode.
> Fix UnicodeDecodeError

- stravalib/client.py
The update_athlete() method in client.py does not work with Python 3.x as 
iteritems() has been removed from Python 3.x.
> use .items() for python2/3 compatibility

- stravalib/attributes.py
There exists a list (tuple actually) of accepted types - str or bytes.
Lines like this:
activity = EntityAttribute("Activity", (SUMMARY, DETAILED))
can be passed as unicode string, that will cause failure.
Adding unicode type to whitelist fix this case.
> Fix unicode string as name of class

- stravalib/model.py
Addresses https://github.com/hozn/stravalib/issues/50
Logged warning: No such attribute starred on entity <SegmentExplorerResult id=None name='Mt Sanitas Trail Climb' resource_state=2>
> add "starred" property on SegmentExplorerResult

- stravalib/model.py
I started getting log noise like this:
WARNING:stravalib.model.Activity:No such attribute pr_count on entity <Activity id=784664167 name=u'Evening commute' resource_state=None>
Looks like this is a new property showing the number of new personal records earned?
> Add new pr_count property.

- stravalib/protocol.py
Some improvements for rate limiting (WIP!):
1. Invoking the rate limiter for every response, not only 200 OK,
2. New rate limit rule for preventing short bursts of requests from reaching limits too soon
> WIP - rate limiter improvements

- stravalib/tests/functional/test_client_rate_limiter.py
- stravalib/tests/unit/test_limiter.py
- stravalib/util/limiter.py
Introducing a new rate limit rule that uses feedback from the Strava API about actual limit usage. It uses variable cool-down periods after each response processed by the client. The cool-down periods depend on the number of request left in the current period, and the priority given to the rule. There's no need to initialize this rule with explicit limits, it will get these from the API responses as well.
> More rate limit improvements

- stravalib/client.py
- stravalib/protocol.py
I was trying to upload a `tcx.gz` file to Strava, but was hitting timeout issues when waiting for the activity to finish processing. However, the initial request actually failed with a 400. This wasn't captured by `upload_activity` because Strava returned a JSON payload in the format: 
```
{u'errors': [{u'code': u'invalid encoding',
u'field': u'gzip',
u'resource': u'upload'}],
u'message': u'Bad Request',
}
```
Both `errors` and `message` aren't in the API documentation. Because `errors`, and not `error` was returned, `upload_activity` did not raise an exception.
I also am saving that response info in `ActivityUploader` instances. This allows a consumer to inspect all of the data returned by Strava.
> Adding more info to ActivityUploader and handling errors

- stravalib/client.py
If there are no errors in the upload response, raise_for_exc raises AttributeError.
> Prevent AttributeError when ActivityUploader has no error

- stravalib/client.py
- stravalib/model.py
This PR adds the RunningRace class and exposes two get functions:
- client.get_running_races(year)
- client.get_running_race(race_id)
For the first method the year defaults to the current year if empty.
See Strava API here:
https://developers.strava.com/docs/reference/#api-RunningRaces
Also while retrieving club members ```get_club_members(club_id=123)```. I noticed that I got some warnings on three attributes (membership, owner and admin) that are not part of the Athlete class. So I added these to the class too.
Let me know if you have any feedback.
> Add RunningRace model and expose get_running_race(s).

- stravalib/model.py
Adds missing `x_swim_totals` attributes to `AthleteStats`. Prevents warnings to be logged, for example:
```
2018-03-29 21:01:35 WARNING (MainThread) [stravalib.model.AthleteStats] No such attribute recent_swim_totals on entity <AthleteStats >
2018-03-29 21:01:35 WARNING (MainThread) [stravalib.model.AthleteStats] No such attribute ytd_swim_totals on entity <AthleteStats >
2018-03-29 21:01:35 WARNING (MainThread) [stravalib.model.AthleteStats] No such attribute all_swim_totals on entity <AthleteStats >
```
Reference from the Strava API documentation: https://developers.strava.com/docs/reference/#api-models-ActivityStats
> Add missing swim activity stats to AthleteStats

- stravalib/protocol.py
Hi there!
First of all, I love this library - thank you for putting it together!
I first started using stravalib over a year ago, before Strava added refresh tokens, and I know straight up access tokens are to be deprecated but for whatever reason (and maybe this is just the case because I first authorized my personal Strava account a couple of years ago) I am not returned a refresh token, just an authorization token so because of that I was getting a key error whenever I executed exchange_code_for_token. A quick get() with a None default solved the problem.
Let me know what you think!
All the best,
Keiron
> refresh_token and expires_at set to None if none are returned

- stravalib/client.py
See https://pythonhosted.org/stravalib/api.html?highlight=kudos#stravalib.client.Client.get_activity_photos
Sorry for the super minor PR - feel free to close this and just include the change in your next commit if you want.
> Fix typo in get_activity_photos (kudos --> photos)

- stravalib/model.py
Before this change `to_dict()` would only return values that were defined on the
local class.
For example, `Bike.to_dict()` would return a dict with a single `frame_type` key
since it's the only `Attribute` defined on the class. The rest of the
attributes are defined on the parent classes (`Gear`, `IdentifiableEntity`, etc.)
This commit makes `to_dict()` also look for `Attributes` defined on parent
classes and includes them in the output as well.
> Make to_dict() include attributes of parent classes

- stravalib/attributes.py
- stravalib/tests/unit/test_attributes.py
Fixes #215. Since 2021-08-11, the Strava API returns an empty list for e.g. the `start_latlng` attribute.
This fix prevents `IndexError`s when deserializing these attributes.
> Fixes IndexErrors when deserializing empty lists as GPS locations

- stravalib/model.py
Changes:
- Will only list the `resourse_state` property if it is set to something
- Won't include a trailing space after the class name if none of the attrs are set
> Tweak __repr__ of BaseEntity objects

- stravalib/client.py
The scope parameter docs were incorrect (presumably out of date).
I copied the docs from the corresponding function in protocol.py.
> Update docs for Client.authorization_url

- stravalib/model.py
This closes #220 
It looks like strava has made some changes to their API. this fixes a bug where a bunch of warnings are thrown given missing attributes for shoes. I have tested this locally but did not look closely at the test suite to ensure tests also work locally. @hozn if you need any changes to this please let me know. But please do know i didn't touch the test suite yet as i still need to set that up and dig into how you have tests setup locally. 
Thank you @yihong0618 for the direction regarding what the issue was!
> fix get_athlete w new attrs for shoes given strava updates to API

- stravalib/tests/functional/test_client.py
- stravalib/tests/functional/test_client_utils.py
- stravalib/tests/functional/test_client_write.py
- stravalib/tests/functional/test_result_iterator.py
- stravalib/tests/unit/test_model.py
Deprecated unittest aliases were removed in Python 3.11 . The recommended aliases are present in both Python 2.7 and Python 3. So the PR is backwards compatible.
assertEquals -> assertEqual
assertAlmostEquals -> assertAlmostEqual
Ref : https://github.com/python/cpython/pull/28268
> Refactor deprecated unittest aliases for Python 3.11 compatibility.

- docs/reference/api/stravalib.client.Client.get_running_race.rst
- docs/reference/api/stravalib.client.Client.get_running_races.rst
- docs/reference/api/stravalib.client.Client.rst
- docs/reference/client.rst
- stravalib/attributes.py
- stravalib/client.py
- stravalib/tests/unit/test_attributes.py
Some activities have unknown or incorrect time zones in the JSON response from Strava, e.g., '(GMT+00:00) Factory'. This change will make the unmarshaller from `TimezoneAttribute` return `None` instead of raising an `UnknowTimeZoneError` (and crashing the overall unmarshalling process).
> Improved unknown time zone handling

- .github/workflows/push-pypi.yml
- changelog.md
This PR:
Fixes the issue where it couldn't find the dist/ dir. essentially to build that way i'd need to upload the archive and then download it in the publish step. That just was getting a lot more complex than it needed to be. 
Thus i opted to simplify the build and just have it all run in one step with conditionals. it also should only run in the stravalib main repo so other contributors don't have to worry about it.
> FIX: pypi build with version & simplify build ✨ 

- stravalib/client.py
- stravalib/model.py
Recently Strava has introduced an option to "mute" an activity (hide it from Home and Club feeds, but keep visible on athlete's profile). From inspecting the activity structure, this `bool` activity setting is called `hide_from_home`. It has been available to all Strava users since September but, unfortunately, has not yet been documented on Strava's API page.
> Add an option to mute Strava activity on update

- stravalib/model.py
I should have caught this issue in the open PR - we just hadn't migrated away from 2.x at the time of this pr.
> Fix: model PR to use str instead of six.texttype

- .github/workflows/build-test.yml
- Makefile
- README.md
- changelog.md
- docs/Makefile
- requirements.txt
closes #261 
So this is an update to the make build that 
1. cleans up the make builds as they were a bit messy especially the docs one
2. adds  sphinx autobuild which is really nice for editing docs as it allows you to run the docs live as you edit them and view your updates in realtime in the browser. this saves a ton of time. 
3. Adds a clean step to clean out files in your dir that are crteated via builds that you'd never want to be in version control 
What we don't get with make is the virtual enviornment setup which might make it easier for a new contributor BUT make does the job. 
Once this PR which is small and the other big one are merged I will submit a new pr to update the builds to call make to streamline everything. That way we have the commands to do things like run CI tests …
> FEAT: Cleanup make files and add docs autobuild

- .github/workflows/build-docs.yml
- .readthedocs.yml
- README.md
- changelog.md
- docs/index.rst
closes #270 
in part but i think we should talk this through in that issue just to ensure we are all on the same page. 
This PR just adds a yml file with instructs readthedocs to build our package using pip. i think that with pip, the version_generated file must get created as long as you have tags locally the version should work.  
It also adds 3 badges to the readme:
* docs build or pass from readthedocs. that will make it easier to identify when a  build goes wrong
* python versions that we support
* current release version on pypi
> Fix: Add readthedocs config file to ensure that stravalib is installed in the build using pip

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- changelog.md
closes #274, #269
Please see the open issue #274 for explanation. 
This pr:
In a separate PR i'll submit a new development guide (the file linked to in this pr). i'm just trying to keep my pr's a bit smaller as that pr was going to be 15 files with all of the changes!
> ADD: code of conduct to repo and update contributing guide with current workflow

- .github/workflows/build-test.yml
- .gitignore
- Makefile
- README.md
- changelog.md
- requirements.txt
closes #262 
This pr adds the code cov integration needed to both push to code cov and get reporting in each PR. 
* you can see the integration in this PR but there's nothing for it to diff against until we merge to master and use it in another PR
* I updated the readme file with a coverage badge as well.
> Add: codecov to build for test coverage

- changelog.md
- stravalib/client.py
- stravalib/exc.py
- stravalib/tests/integration/test_client.py
- stravalib/unithelper.py
These new tests make sure that all (implemented, see #282) endpoints used for creating and updating objects are covered.
It adds several deprecation warnings (both at runtime and in the documentation) for method parameters that are not supported anymore by Strava.
> Add integration tests for all POST/PUT client methods

- .coveragerc
Its a bit annoying that that test files are in the code cov results when run locally. this just adds a config file to ignore them so results look like this:
```bash
---------- coverage: platform darwin, python 3.8.13-final-0 ----------
Name                         Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------
stravalib/__init__.py            2      0      0      0   100%
stravalib/_version.py            2      0      0      0   100%
stravalib/attributes.py        170     19     62     13    83%
stravalib/client.py            439    180    205     15    55%
stravalib/exc.py                34      3      0      0    91%
stravalib/model.py             709    126     78      2    76%
stravalib/protocol.py          130     39     48     15 …
```
> Fix: dont include tests in code cov results

- .github/workflows/build-test.yml
- CONTRIBUTING.md
- README.md
- changelog.md
- docs/get-started/overview.rst
- docs/index.md
- requirements.txt
- setup.cfg
- stravalib/attributes.py
- stravalib/client.py
- stravalib/exc.py
- stravalib/tests/unit/test_model.py
- stravalib/tests/unit/test_unithelper.py
- stravalib/unithelper.py
closes #281
Replaces the dependency on `units` with the `pint` library since the former is no longer maintained. Adds helper classes and functions to maintain backward compatibility. Unless client code uses internals of the `units.Quantity` type, the result of this change should be compatible with existing code.
The `units` package is no longer maintained and may lead to dependency resolution errors (e.g., in pipenv 2022.11.30).
> Units2pint

- stravalib/client.py
- stravalib/model.py
- stravalib/tests/auth_responder.py
- stravalib/tests/integration/test_client.py
- stravalib/tests/unit/test_client_utils.py
- stravalib/tests/unit/test_limiter.py
Adds support for nested model attributes. This ensures that entities within entities (e.g., `ActivityTotals` as part of `AthleteStats`) are also of the correct extended types and will be backward-compatible.
In addition to previous work on this branch, this PR also replaces the following legacy entities:
- ActivityComment
- ActivityPhotoPrimary
- ActivityPhotoMeta
- ActivityKudos
> Nested model attributes

- .github/PULL_REQUEST_TEMPLATE.md
And removes CI check. CI state should be obvious.
Tiny improvement to this template, to remind contributors to update the changelog.
> Adds changelog check to PR template

- stravalib/field_conversions.py
- stravalib/model.py
- stravalib/tests/unit/test_model.py
Closes #330
Fixes enum lookup behavior. Enums in the model should be converted to their basic value for backward compatibility. Pydantic should support this out of the box by providing config, but unfortunately, it doesn't work for collections of enums in model subclasses (see https://github.com/pydantic/pydantic/issues/5005).
This fixes the order of attribute lookup because enums do not raise `AttributeError` when being assigned new attributes.
NA, will happen when merging into master
> Fix: Corrects attribute lookup for enum values

- stravalib/field_conversions.py
- stravalib/model.py
- stravalib/strava_model.py
- stravalib/tests/resources/strava_swagger.json
- stravalib/tests/unit/test_field_conversions.py
- stravalib/tests/unit/test_model.py
Strava introduces ClubActivity and ClubAthlete types that replace the existing SummaryActivity and SummaryAthlete types that are part of a club.
A bug fix in the datamodel-code-generator package now ensures that no enum types are created. This causes some slight changes in enum handling.
Strava API change
> Adds some Strava API changes, and datamodel-code-generator bug fix

- changelog.md
- stravalib/tests/integration/test_client.py
- stravalib/tests/unit/test_unithelper.py
- stravalib/unit_registry.py
- stravalib/unithelper.py
closes #335 
The `Quantity` class meant to provide backward compatibility with the `units` package did not correctly handle arithmetic and comparison operators. This corrects the issue.
> Fix: allows arithmetic and comparison between multiple quantities

- requirements.txt
This just fixes the current PR where docs are not building due to a bug in the [pydata sphinx theme ](https://github.com/pydata/pydata-sphinx-theme/issues/1226)
docs work with version 0.12 so i'm pinning to that version until i see the bug is fixed.
> Fix: pin pydata sphinx theme to avoid icon error issue

- changelog.md
- examples/strava-oauth/requirements.txt
This is necessary to prevent the reported security vulnerability https://github.com/stravalib/stravalib/security/dependabot/1.
> Bumps Flask for example code

- changelog.md
- pyproject.toml
- stravalib/exc.py
More work related to #373. This took it easy and did the exception file.
> type annotation for exc.py

- requirements.txt
The introduction of Pydantic 2.0 led to (at least) one failure in stravalib. This pins pydantic to the (current) latest v1.
NA, this PR is nothing but a cherry-picked commit from a feature branch.
> Hotfix: pin to pydantic v1

- stravalib/model.py
This is just a tiny modification to make typing for naive_datetime more explicit. We will need to modify it to not use pydantic in the future but for now by typing it following parse_datetime specs it will be easier to understand inputs when we write more tests.  we may want to not accept certain of these formats and can have a discussion about what types of datetime formats we will accept here.
this is so small i didn't add a changelog update.
> Fix: minor enhancement in naive_datetime types

- changelog.md
- pyproject.toml
- stravalib/client.py
- stravalib/model.py
Add type annotations to the client file. See #373
Still need to fix a couple small typing error and would be best to address #383
first as it relates to the test that are now failling.
> Typing client file

- changelog.md
- stravalib/client.py
- stravalib/model.py
closes #394
This addresses the issue of validate having the same name as pydantic.BaseModel and as such raising errors when typing stravalib... but also leaving us open to unexpected behavior. 
tests ARE running locally. i know that it makes sense to add some tests here but i'm still getting to know our test suite and am not quite confident enough YET to add tests. but this should fix the typing warning we are getting in #387 as a starting place.
> Fix: rename validate to validate_token

- .gitignore
- changelog.md
- docs/conf.py
- pyproject.toml
- requirements.txt
- stravalib/client.py
- stravalib/model.py
closes #375 
This should fix 375 - the warning when building docs
This is a small issue
1. if docs are missing docstrings they won't appear at all in the documentation.
2. If a class inherits from another class but is missing a pass, it also can't render properly making it difficult for pydantic-autodoc to properly render the expected JSON.
This fixes that issue in model.py and also addresses a few other docstring related items.
- [x ] This is a documentation update
> Fix:  model.py docstrings and typing

- pyproject.toml
Relates to #373
Includes the newly fixed strava_model.py file in type checking
> Include strava_model in type checking

- .readthedocs.yml
- changelog.md
closes #411
Our docs are currently failing builds in read the docs.
i didn't update the changelog on this one but could. it's pretty minor if this fix works
> Fix: update Readthedocs config file and add autobuild permissions for prs

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation-issue.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- changelog.md
closes #408
This is just a way to help guide uses to better bug reports that we can begin to evaluate more easily
you can see what the [templates look like in my repo here!](https://github.com/lwasser/stravalib/issues/new/choose)
> Add: Issue template forms for users to create better bug and documentation reports

- .github/workflows/build-test.yml
- README.md
- changelog.md
- pyproject.toml
- stravalib/client.py
- stravalib/field_conversions.py
- stravalib/model.py
- stravalib/protocol.py
- stravalib/strava_model.py
- stravalib/tests/__init__.py
- stravalib/util/limiter.py
Remove supports for python 3.8 following discussion on #301
- Remove python 3.8 support and ci run against that versions
- run pyupgrade for python 3.9+
> Drop python 3.8 support

- .gitignore
- .readthedocs.yml
- changelog.md
- docs/contributing/build-release-guide.md
- docs/contributing/development-guide.md
- noxfile.py
- requirements.txt
closes #395
This change adds Nox to our build workflow. Right now we are using Make for everything. Nox is much cleaner because it's python and as such easy to read. it also supports virtual environments and running things across various versions for local debugging. 
This pr does NOT include building our package but that step will be easy to add. I just wanted folks to test it out to see if everyone is comfortable with moving to nox and removing the old-school Makefile that is much harder to read / maintain (IMO) :) with less fun features like environments and such for robust test dev locally.  ✨ 
This is an infrastructure update!
tests to support …
> Add: nox config for docs, tests

- .pre-commit-config.yaml
- changelog.md
- examples/strava-oauth/server.py
- pyproject.toml
- src/stravalib/model.py
closes #427
Configure ruff like flake8 was and replace it is CI
Also replace isort
> Replace flake8 and isort by ruff

- changelog.md
- src/stravalib/field_conversions.py
- src/stravalib/model.py
Partial fix for #437
When an attributes represents a duration we parse it directly with pydantic
instead of using field conversion to convert the value when attribute is
accessed.
This allow to have the right type annotation for those field.
> fix type for timedelta element on models

- changelog.md
- src/stravalib/model.py
closes #443
The `sizes` attribute of the `ActivityPhoto` was incorrect, leading to parsing errors. This is fixed.
I didn't add a test as this a an undocumented API method that can change any time.
> FIX: corrects model for ActivityPhoto

- .pre-commit-config.yaml
- changelog.md
- pyproject.toml
There is no issue for this. I just see that codespell if failing a simple pre-commit update here #442 so i wanted to make a quick fix to it ignored that tests/resources dir. i'm still perplexed as to how it things there is a word in that line of the file.  
This is just a tiny config change to how codespell runs
> Fix: codespell ignore resources dir

- MANIFEST.in
- changelog.md
closes #307
This is a tiny pr that just removes examples from our sdist. i had opened #307 because when i built i was getting funny results in the sdist with all of the git history there. i'm no longer seeing that behavior so i just am making a tiny cleanup PR and we can then remove another issue from our issue tracker! 
> Fix: minor - remove examples from sdist

- changelog.md
- docs/contributing/how-to-contribute.md
- docs/contributing/intro.md
- docs/get-started/index.md
- docs/index.md
- src/stravalib/client.py
when i tried to make the release i had to dig around for our contributing docs. it made more sense to add them to the top header of our documentation. In rebuilding i noticed some syntax errors in the client.py file so i fixed those as well so things render properly and don't throw sphinx warnings. 
> Fix: add contributing docs to top bar nav in docs

- .github/workflows/build-test.yml
- .gitignore
- changelog.md
- noxfile.py
closes #468 
Adds the token that i added to our repo to the build
I am not sure this needs another changelog input from me.
> Fix: make sure code cov reports generate and upload

- changelog.md
- src/stravalib/client.py
closes #238
This is a simple pr that removes a method that was targetting a now unsupported endpoint in the strava API. 
please note that i did have a look at the tests but didn't find any relevant to this removal. now let's see if i broke anything given that is what i am best at.
> Remove: unsupported delete_activity method

- .github/workflows/build-docs.yml
- .github/workflows/build-test.yml
- .github/workflows/check-strava-api.yml
- .github/workflows/push-pypi.yml
- .github/workflows/type-check.yml
When we run all of our actions we get this error which relates to node js 16 actions being deprecated. This is a security issue but also it's good practice to keep actions current. This pr only updates actions to their most current versions! No code is going to be impacted by merging and everything should run as usual! 
i didn't update the change log for this one as it's a tiny update.
> Fix: update actions to current versions

- changelog.md
- noxfile.py
- pyproject.toml
- src/stravalib/client.py
- src/stravalib/tests/unit/test_model.py
closes #358
This removes the deserialize method and replaces calls to is with pydantic.parse_obj. It also cleans up the tests accordingly.
> Remove: deserialize method in favor of pydantic.parse_obj()

- docs/contributing/development-guide.md
- pyproject.toml
closes #254 
This is a TINY pr that will finish off #254 where we discussed when we drop versions of Python that we support. 
Does anyone have opposition to us dropping Python 3.9 at this point? 
The specific guidelines relate [to this spec](https://scientific-python.org/specs/spec-0000/)
which suggests supporting versions of Python for up to 3 years post release. 
i didn't update the changelog for this either as it's minor. but if we drop 3.9 then i will refer to this documentation change in that pr via a changelog update.
> Fix: update docs around python support

- .github/workflows/build-docs.yml
- .github/workflows/build-test.yml
- .github/workflows/push-pypi.yml
- changelog.md
- noxfile.py
- pyproject.toml
closes #487 
This drops Python 3.9 from all builds and adds 3.12. 
> Add/Remove: Add support for python 3.12 and drop 3.9

- .github/workflows/push-pypi.yml
I am doing a quick patch of our publish action
* upgrade setup-python to v5 to avoid node JS 16 errors / warnings
* Make sure twine is installed for check dist/ step
> Fix: update action deps and versions

- src/stravalib/model.py
- src/stravalib/tests/integration/test_client.py
- src/stravalib/tests/unit/test_model.py
closes #498
Removes `BackwardCompatibilityMixin` and its related `_field_conversions` model attributes. As a result, all the previously "modified" types that, e.g., returned a pint `Quantity` object instead of a unitless float now return the base type. Later PRs will re-add these customized types but will ensure they match the parent type.
But the new test is skipped until we implement the new custom types.
Let's add one changelog entry for when the complete `pydantic-v2` branch merges into `main`?
> Remove backward compatibility mixin

- src/stravalib/client.py
- src/stravalib/model.py
- src/stravalib/tests/integration/test_client.py
This is a tiny PR to show how making the Strava type hierarchy explicit in our client responses can improve type-checking accuracy and prevent user confusion (see #494).
This approach can be used to resolve #499.
> Adds Strava type hierarchy for Activity type

- src/stravalib/client.py
- src/stravalib/model.py
- src/stravalib/strava_model.py
- src/stravalib/tests/integration/test_client.py
This adjusts the return types for the athlete/clubs endpoint. It also updates a test and modifies the return object type to be an iterator vs a list. 
#506
> Fix: fix return types - athlete clubs endpoint

- src/stravalib/client.py
- src/stravalib/model.py
This pr adjusts the expected return types following strava's spec but also looking at the actual return elements in postman. 
Also addresses part of #506
> Add: correct type returns following clubs/{id}  & clubs/{id}/activities spec

- src/stravalib/client.py
- src/stravalib/model.py
- src/stravalib/tests/integration/test_client.py
- src/stravalib/tests/unit/test_model.py
This corrects the type hierarchies for `Gear` and `Athlete` types, + several other typing issues I encountered in the `pydantic-v2` branch. The remaining (3) typing issues will be resolved by #510 .
> Gear and Athlete type hierarchies (+ naive_datetime typing fixes)

- src/stravalib/model.py
I haven't opened an issue 
This is a tiny code change to remove `Optional` from our typing and replace it with `|` given we did drop python 3.9 support. 
if we are worried about this breaking builds for anyone using 3.9 we could add 
`from typing_extensions import Annotated` for backwards compatibility. but 3.9 will be end of life in the fall so in theory folks should be upgrading to 3.10 at this point. 3.13 is being actively worked on. 
> Fix: remove Optional throughout and replace with |

- docs/conf.py
- docs/index.md
- docs/reference/client.rst
- docs/reference/model.rst
- docs/whats-new/changelog.md
- docs/whats-new/stravalib-2.md
- src/stravalib/model.py
This PR just cleans up our docs and adds a banner + a what's new section.
Right now the docs won't build because of a recursion issue mentioned in #538 which we need to fix first. i'm going to take a quick look at that next to see how involved it will be to address it. because of how we're building our docs, i'm not sure how to create the :noindex: flag to ignore the recursion issue (which is a duplicated attribute in two classes. (this happens a few times). 
UPDATE:
i actually looked into this and am not sure how to handle things here. We could merge just to work on the discussion around what's changed. but it seems like there may be some inheritance issues that we need to sort out first
> Add: what's new section to the docs

- changelog.md
- src/stravalib/client.py
- src/stravalib/model.py
I know that this wasn't in our list of issues but the photos endpoint diverged from the Spec so I just cleaned it up a bit.  
The changes here just realign things with the strava spec where possible. i do understand that get_activity_photos is not a supported endpoint by strava currently. but i was able to get it to work after a lot of digging and then a realization that I should have just read the docstring for that method 🙃 first (instead of last) 🙈 i'm sorry for the excessive pings yesterday @jsamoocha
> Fix: Photos endpoint cleanup

- src/stravalib/client.py
- src/stravalib/model.py
I could be missing something here. But part of the docs issues related to duplicated attributes. 
When i looked at model.ActivityComment is had a single attribute athlete and it inherited from BaseModel. however in strava_model there is a Comment object that has the same attr +. The spec calls for a return of a Comment object so I just removed the model.ActivityComment and imported strava_model.Comment instead. 
If there was some reason that we added this, lt's keep it. But it seems to be at this point it's a redundant class. I wondered if maybe the strava_model didn't have `Comment` before and now it does.
> Activity Comment cleanup

- .codecov.yml
This is a tiny pr to relax the requirements for code cov. this way it won't fail a pr if the test coverage is within 10% of main's current state.
> fix(codecov): relax code coverage requirements

- docs/conf.py
closes #562 
This may be the fix to the broken banner link to our migration guide. let's see!  
This just makes the link relative rather than /link
> fix: banner url relative

- changelog.md
- src/stravalib/model.py
closes #570 
Some field of ActivitySummary were only casted into our custom type on DetailActivity. This PR addresses that. 
Hopefully I've found them all.
I feel like this change is not breaking but not 100% sure. I'd take the opinion of the other dev on that
> Specialize type for on summary activity

- .all-contributorsrc
I missed a comma in the json config file 🙈
> docs(fix): missing comma in all contribs json

- changelog.md
- src/stravalib/model.py
- src/stravalib/tests/unit/test_model.py
closes #583
Ensures ActivityType instances can be compared to str. This prevents an undocumented breaking change from stravalib v1.
Updated existing test.
> FIX: ensures ActivityType instances can be compared to str

- docs/get-started/activities.md
- src/stravalib/client.py
closes #233 
This is a tiny PR that clarifies how streaming data resolution works with stravalib and strava. I also added a note to the 
docstring so the user understands what `resolution=None` returns following @djcunningham0  issue.
this is a tiny update, so i didn't include a changelog item for it.
> fix(docs): tiny update to streaming data

- changelog.md
- src/stravalib/model.py
closes #594
Several undocumented attributes were incorrectly part of `DetailedActivity` (instead of `SummaryActivity`)
> Fix summary activity undocumented attributes

- .github/workflows/build-test.yml
This is a small patch pr that just updates the version of the codecov action we're using as I'm noting some flakiness in cov reports. I'll merge this .
> fix: update codecov in build

- .github/.dependabot.yml
- changelog.md
- src/stravalib/client.py
- src/stravalib/protocol.py
- src/stravalib/tests/integration/test_client.py
- src/stravalib/tests/unit/test_protocol_auth.py
closes #552
This ensures `exchange_code_for_token` returns the optional `SummaryAthlete` object if requested.
> feat: Return optional SummaryAthlete via exchange code for token with user request

- .github/workflows/push-pypi.yml
- changelog.md
closes #617
This pr describes and adds trusted publishing to stravalib. Right now we are publishing via a token. This is ok but token leaks are real AND trusted publishing is a more secure and preferred route to publishing. 
A few things left to do here
> fix: add trusted publisher setup to stravalib

- changelog.md
- docs/get-started/authenticate-with-strava.md
closes #631
Documentation fix regarding naming of expected environment variables for client_id and client_secret.
> Fix auto refresh token env vars

- .github/workflows/build-docs.yml
- .github/workflows/build-test.yml
- .github/workflows/check-strava-api.yml
- .github/workflows/publish-pypi.yml
- .github/workflows/type-check.yml
- changelog.md
Narrows permissions used in GitHub Actions to only what is needed to run.
Refs: https://docs.zizmor.sh/audits/#excessive-permissions
> chore(ci): narrow permissions used in actions
