- stravalib/model.py
- stravalib/tests/functional/test_client.py
Failed to add a relevant property to the Activity model for get_related_activities in previous pull request.
> Adding related property to Activity

- stravalib/attributes.py
- stravalib/client.py
- stravalib/exc.py
- stravalib/model.py
- stravalib/tests/functional/test_client.py
Adds functionality detailed at http://strava.github.io/api/v3/athlete/#stats.
Moved statistic fields out of athlete and into new AthleteStats model as per API changes.
> Adding Athlete Statistics methods

- stravalib/protocol.py
- stravalib/tests/functional/test_client_utils.py
See http://strava.github.io/api/v3/oauth/#get-authorize - added an assert that the scope is correct.
> Updates to authorization_url plus tests

- stravalib/attributes.py
- stravalib/model.py
- stravalib/tests/functional/test_client.py
- stravalib/tests/resources/activity-manual.3.json
- stravalib/tests/resources/activity.3.json
- stravalib/tests/resources/athlete.2.json
- stravalib/tests/resources/athlete.3.json
- stravalib/tests/test_attributes.py
Adds the following updates documented in the [changelog](http://strava.github.io/api/v3/changelog/):
* Removes `truncated` from Activity model
* Adds `total_photo_count` to Activity model
* Adds `athlete_type` to Athlete model -- this required a new attribute class `ChoicesAttribute`
> Updates from Changelog 

- stravalib/client.py
Unfortunately gave up writing a test. BTW, how do you launch them?
> Fix uploading activity as a text.

- stravalib/model.py
Added device_watts to BaseEffort class
Removed a redundant line for device_watts in the Activity class
> Slight fixup for device_watts

- stravalib/client.py
Adds support for the deauthorization functionality of the Strava v3 API detailed at http://strava.github.io/api/v3/oauth/#deauthorization
> Add support for deauthorization

- stravalib/model.py
as per changelog March 21 2016
> Adding has_heartrate attribute to Activity 

- stravalib/client.py
- stravalib/model.py
- stravalib/tests/functional/test_client.py
Hello there!
This is my very first public PR. I needed the ability to retrieve routes and tried to code it. So far it's been working for me. Don't hesitate to amend or improve and thanks a lot for the lib!
C.
> Retrieve Routes

- stravalib/client.py
- stravalib/model.py
- stravalib/protocol.py
Still TODO: list subscriptions, delete subscriptions, a few other small things
> Initial webhook events support #77

- stravalib/client.py
> Some comments for `create_subscription()`

- stravalib/client.py
the delete_activity function wasn't working for me. with the proposed change it does.
> fix for delete_activity

- stravalib/client.py
- stravalib/model.py
- stravalib/tests/functional/test_client.py
Hello there!
This is PR to retrieve all 4 streams available for routes: [https://strava.github.io/api/v3/streams/#routes!](https://strava.github.io/api/v3/streams/#routes)
The implementation is very much inspired by other calls to retrieve streams.
Thank you again for this great library!
> Get streams for a route

- stravalib/client.py
I would like to use client.update_activity w9th a device_name parameter
> added device_name to update_activity

- stravalib/model.py
fix warning for missing attribute
> Add utc_offset attributes for Activity

- stravalib/model.py
The Segment's PR can be used to compare with other Athlete PR easily without multiple requests.
> Add new attributes for Segment

- stravalib/model.py
> Commented out utc_offset

- README.md
As I'm getting familiar with stravalib I wrote short instruction to build, install and run tests, since this may not be obvious for new contributors.
> Building from sources

- stravalib/client.py
- stravalib/protocol.py
- stravalib/tests/functional/test_client_utils.py
> Updated scopes for new Strava OAuth #164

- README.md
It was a bit ambiguous about how the expires_at token was used; added a small snippet to clarify.
> Update documentation elaborating on expires_at and refresh_access_token.

- stravalib/model.py
> Import ABC from collections.abc for Python 3 compatibility.

- stravalib/model.py
`average_grade_adjusted_speed` appears to be a new property on the Split model
> Adding average_grade_adjusted_speed property to the Split model

- stravalib/client.py
- stravalib/protocol.py
+ Removed unused attributes in webhook creation.
> Now webhooks use the same domain as the rest of API.

- stravalib/client.py
Fix a couple typos and update function comments to match protocol.py
> Comment typos/fixups

- stravalib/attributes.py
> deal with tzname without offset and timedelta in string format

- stravalib/model.py
Source:
http://developers.strava.com/docs/reference/#api-models-SummaryActivity,
http://developers.strava.com/docs/reference/#api-models-DetailedActivity
Fixes: #153
> Fix a few fields in Activity model

- README.md
- examples/strava-oauth/README.md
- requirements.txt
- stravalib/attributes.py
- stravalib/client.py
- stravalib/exc.py
- stravalib/model.py
- stravalib/protocol.py
- stravalib/tests/auth_responder.py
- stravalib/tests/functional/__init__.py
- stravalib/tests/functional/test_client.py
- stravalib/tests/functional/test_client_rate_limiter.py
- stravalib/tests/functional/test_client_write.py
- stravalib/tests/functional/test_result_iterator.py
- stravalib/tests/unit/__init__.py
- stravalib/tests/unit/test_attributes.py
- stravalib/tests/unit/test_client_utils.py
- stravalib/tests/unit/test_model.py
- stravalib/unithelper.py
- stravalib/util/limiter.py
fix: #231 
@jsamoocha @lwasser @hozn
> feat: drop python2 support

- stravalib/client.py
- stravalib/tests/integration/test_client.py
Fully tests upload_activity(). (part of #250)
I could use some advice on if/how to use `FutureWarning`s in case of seemingly deprecated API parameters.
> Test client - upload_activity

- stravalib/model.py
> Fix: add new attributes for bikes according to updates to Strava API

- .github/workflows/build-docs.yml
- .github/workflows/build-lint.yml
- .github/workflows/build-test.yml
- changelog.md
see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Fix:  deprecated set-output command 

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/release-pull-request-template.md
- changelog.md
This just adds pull request templates here so we can more easily merge #290
> Add: pull request templates to repo

- changelog.md
> Release 1.1.0

- changelog.md
- stravalib/client.py
- stravalib/tests/integration/test_client.py
- stravalib/tests/unit/test_client_utils.py
closes #308
When calling `client.upload_activity` and `activity_file` type is `bytes`,
I get this error
`Invalid type specified for activity_file: bytes`
*If you are having a hard time getting the tests to run correctly feel free to 
> fix(upload_activity):  - fix unable to read activity_file with type bytes

- Makefile
- changelog.md
- pyproject.toml
- stravalib/exc.py
closes #319
Makes sure tests don't raise any internal warnings that we generate on purpose.
> Fix: Internal warnings should be ignored in tests

- changelog.md
- stravalib/attributes.py
*The text above will ensure the issue will be closed when this PR is merged*
The `LatLon` object will be written to file as a string in the format `"{lat},{lon}"`. However, on `unmarshal()`, it is expected to be a list. This results in the value being read wrong. For example, `"start_latlng": "47.441764,-121.672241"` will be result in a a `LatLong` object with `lat` = `4` and `lon` = `7`.
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix LatLon unmarshal: deal with string type

- changelog.md
* [An overview of our release workflow can be found in our documentation.](https://stravalib.readthedocs.io/contributing/build-release-guide.md)
* [Before making a release be sure to check out test PyPI](https://pypi.org/project/stravalib/) to ensure that the build is working properly.
> RELEASE 1.2 ✨

- changelog.md
I took time to get the changelog updated. Please feel free to add / update fix - i just went through the commit history and added all pr's to the changelog. I included @oliverkurth on this as well given a fix that they submitted was integrated into this branch as well! 
> ✨Release 1.3.0rc0 ✨ 

- .github/workflows/check-strava-api.yml
This is a tiny PR with 2 additions to the workflow that updates the model:
- besides updates to the schema/entities, the workflow will also detect changes to the API (as in endpoints and their parameters)
- in case of changes (and a generated PR), the PR body will have a reminder to update the changelog (I don't think we need to include the full PR template for these bot-generated PRs)
Manually tested these changes in another repo.
This is too trivial for the changelog, I guess.
> Strava api check improvements

- changelog.md
- stravalib/model.py
This adds the Rate of Perceived Exertion (RPE) to the activity model.
> Add: Adds RPE to activity model

- changelog.md
> Bump to version v1.3.0

- changelog.md
- stravalib/model.py
closes #368 
*The text above will ensure the issue will be closed when this PR is merged*
Added a field override in class Segment to support all activity types as the actual Strava API does provide segment efforts for any GPS based activity even though the documentation only states Run and Ride as allowed types.
I am not sure whether this requires additional tests, it passes all integration test and I did test it with activities including segments other than Run or Ride (I was not able to get the functional tests to pass even before the change).
> Add field override for class Segment

- changelog.md
* [An overview of our release workflow can be found in our documentation.](https://stravalib.readthedocs.io/contributing/build-release-guide.md)
* [Before making a release be sure to check out test PyPI](https://pypi.org/project/stravalib/) to ensure that the build is working properly.
The changelog should look something like this:
```
* Add: Add an option to mute Strava activity on update (@ollyajoke, #227)
* Fix: add new attributes for bikes according to updates to Strava API to fix warning message (@huaminghuangtw, #239)
* Change: Improved unknown time zone handling (@jsamoocha, #242)
@jsamoocha, @yihong0618, @tirkarthi, @huaminghuangtw, @ollyajoke, @lwasser
```
> Bump to version 1.3.1

- stravalib/client.py
- stravalib/util/limiter.py
Fix the first two items of #375. The display after the fix looks like this
> fix two error in documentation

- changelog.md
I'll merge this immediately as it has an important fix.
> Release 1.3.2

- changelog.md
- pyproject.toml
Adds pydantic pin to install dependencies
> Pins pydantic in dependencies

- changelog.md
- stravalib/client.py
- stravalib/tests/integration/test_client.py
closes #383 and closes #367
Update the client's methods to get stream to match the current strata API.
> Fix stream methods

- changelog.md
- stravalib/protocol.py
- stravalib/util/limiter.py
This pr begins to (finally) address #326 which i started a while back. There are a few small questions related to pep compliance that i'll comment on. we can decide to ignore E731 in the flake8 settings if we wish. I did not update any docstrings i just restructured and cleaned up PEP 8 issues.
> Fix: Flake 8 and numpy docstring updates addressing #326

- changelog.md
- stravalib/util/limiter.py
Simple fix of documentation formatting that some how ended up formatted weirdly.
Didn't open an issue as the change is really straightforward.
> Fix docstring formatting in SleepRateLimitRule

- .github/workflows/build-docs.yml
- .github/workflows/build-test.yml
- .github/workflows/push-pypi.yml
- .github/workflows/type-check.yml
- changelog.md
- docs/conf.py
- docs/get-started/authenticate-with-strava.rst
Updated all instances of master -->main
> Fix ci: Update CI and docs to reflect new main branch default

- .github/PULL_REQUEST_TEMPLATE.md
- changelog.md
* [An overview of our release workflow can be found in our documentation.](https://stravalib.readthedocs.io/contributing/build-release-guide.md)
* [Before making a release be sure to check out test PyPI](https://pypi.org/project/stravalib/) to ensure that the build is working properly.
> Release 1.4 ✨

- changelog.md
- pyproject.toml
- stravalib/field_conversions.py
- stravalib/unithelper.py
More works on #373
It done!! I've added type annotation to the last file from the library!
> Add: typing field_conversions & unithelper modules

- changelog.md
- pyproject.toml
This is the last step to close #373 !!!
Just adding the marking file to mark the package as PEP 561 compliant
> Publish type annotations

- .pre-commit-config.yaml
- README.md
- changelog.md
- docs/contributing/development-guide.md
- examples/strava-oauth/README.md
- examples/strava-oauth/server.py
- pyproject.toml
- stravalib/__init__.py
- stravalib/client.py
- stravalib/model.py
- stravalib/strava_model.py
- stravalib/tests/auth_responder.py
- stravalib/tests/functional/test_client_rate_limiter.py
- stravalib/tests/integration/strava_api_stub.py
- stravalib/tests/resources/strava_swagger.json
- stravalib/unithelper.py
closes #391 
This adds two more hooks to our infrastructre - blacken-docs and codespell. it allso applies both on our 
code base. 🎉 
> Add: blacken-docs and codespell to build! 🚀 

- changelog.md
- src/stravalib/model.py
- src/stravalib/tests/integration/test_client.py
closes https://github.com/stravalib/stravalib/issues/432
See https://github.com/stravalib/stravalib/issues/432 for a detailed explanation of the issue. This is a fix I made that works, but I don't know if it's the correct way of doing it, so I'm putting it here for review. Essentially when downloading activities (that aren't rides and runs) that have segments, Pydantic fails to validate the activities because it's expecting the `ActivityType` in the `Segment` in the `SegmentEffort` in the `Activity` to be either ride or run. Since Strava has been adding segments for new activity types, this breaks.
If you are fixing a bug or adding a feature, we appreciate …
> Relax Segment ActivityTypes

- changelog.md
* [An overview of our release workflow can be found in our documentation.](https://stravalib.readthedocs.io/en/latest/contributing/build-release-guide.html)
* [Before making a release be sure to check out test PyPI](https://test.pypi.org/project/stravalib/) to ensure that the build is working properly.
The changelog should look something like this:
```
* Add: Add an option to mute Strava activity on update (@ollyajoke, #227)
* Fix: add new attributes for bikes according to updates to Strava API to fix warning message (@huaminghuangtw, #239)
* Change: Improved unknown time zone handling (@jsamoocha, #242)
@jsamoocha, @yihong0618, @tirkarthi, @huaminghuangtw, @ollyajoke, @lwasser
```
Once this PR is merged you …
> Release 1.5

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/check-strava-api.yml
- .pre-commit-config.yaml
- changelog.md
closes #438 
I BROKE @jsamoocha ci build. 
y'all - this should fix the CI bug but let's see. it's referencing files that are now living in a src/ dir rather than a flat layout that we had before.
> Fix: CI broken given new src layout

- src/stravalib/client.py
After updating to mypy 1.7 some ignore comment are not longer needed and are now
removed.
This does not requires a mention in the changelog
> Mypy fix after version update

- changelog.md
- src/stravalib/exc.py
- src/stravalib/protocol.py
- src/stravalib/tests/unit/test_client_utils.py
- src/stravalib/unithelper.py
- src/stravalib/util/limiter.py
> ✨ Release 1.7 ✨

- src/stravalib/model.py
closes #326 
This is just a bunch of small updates to docstrings - i am finally following up on 326.  
I don't think this requires a changelog entry. it's more housekeeping
> Fix docstrings in model.py 

- src/stravalib/strava_model.py
I saw differences between the Pydantic v2 generated model and the version in #492. This PR replaces `strava_model.py` by a version we can expect to come out of the code generator. Based on migration issues, failing tests, or backward compatibility we like to maintain, we may need to further tweak the code generator tool.
Tests should be dealt with in #492 
Not applicable here.
> Modifies generated model by using Pydantic v2

- src/stravalib/client.py
- src/stravalib/model.py
- src/stravalib/tests/integration/test_client.py
This fixes the type hierarchy for athlete-related objects.
> Athlete stats

- src/stravalib/client.py
- src/stravalib/model.py
- src/stravalib/tests/integration/test_client.py
Adds type hierarchy and associated updated for Segment/SummarySegment types, See #499,  #506.
> Summary segments

- src/stravalib/client.py
closes #513 
Tiny pr to remove deprecated methods. 
There are no tests associated with these endpoints / methods that i can see.
> Fix: remove deprecated client methods

- src/stravalib/model.py
- src/stravalib/tests/unit/test_model.py
Tiny PR for adding the `SummarySegmentEffort` superclass.
> Adds SummarySegmentEffort superclass

- changelog.md
- src/stravalib/model.py
- src/stravalib/tests/unit/test_model.py
closes #521
Add @lwasser's test from #491 plus minor changes, namely checking if an input string is an integer.
_If you are having a hard time getting the tests to run correctly feel free to
ping one of the maintainers here!_
> Add `naive_datetime()` test to the `pydantic-v2` branch.

- src/stravalib/client.py
- src/stravalib/model.py
- src/stravalib/tests/unit/test_model.py
> Checks for activities/id endpoint 🙈 

- src/stravalib/client.py
- src/stravalib/model.py
this addresses the activities/{id}/zones endpoint (and will impact the lazy loaded option in /activities/{id}
addresses in part #506
> Update: Activities/{id}/zones  & Laps

- src/stravalib/client.py
- src/stravalib/model.py
- src/stravalib/strava_model.py
closes #510 
Note: i'm a bit unsure of how to handle docstrings in this case. I worry that some users will be confused by what a Sequence is. We are still technically passing lists and dictionaries so i'd love input on the best way to document this properly! i have only begun to migrate the list objects so far. 
This is a start to the migration to more flexible object typing that will support the overrides that we have to implement to support actual strava responses. 
> Fix: Migrate to covariant types to fix typing (in some places)

- src/stravalib/model.py
Reverts stravalib/stravalib#532
Merged too fast, this will create a lot of conflicts with the PR I'm working on.
> Revert "Fix: remove Optional throughout and replace with |"

- .pre-commit-config.yaml
- CODE_OF_CONDUCT.md
- docs/whats-new/changelog.md
This is a tiny pr that just updates pre-commit hooks. so we can avoid more CI errors! it also fixes a spelling issue that codespell found.
> Update precommit + fix docs build issue

- docs/conf.py
- docs/contributing/intro.md
- docs/index.md
- docs/whats-new/changelog.md
- docs/whats-new/stravalib-2.md
- noxfile.py
i did another pass on the docs and found a few bad links and missing nav bars. This just cleans that up.
> Fix: bad link & a few other doc issues

- docs/get-started/overview.rst
closes #502 
This should be the last bit of documentation required to close #502. I just modified the existing "Overview" subsection of "Getting Started" to reflect the changes in the enhanced types.
> Fix enhanced types doc

- changelog.md
- src/stravalib/client.py
- src/stravalib/tests/integration/test_client.py
closes #508 
I'm having some issue getting the test to run. The new method runs as expected my I use my token but the test is actually failling. Printin the `raw` variable shows that it is this list that I don't understand when it comes from
```
[{'distribution_buckets': [{'max': 0, 'min': 0, 'time': 1498}, {'max': 50, 'min': 0, 'time': 62}, {'max': 100, 'min': 50, 'time': 169}, {'max': 150, 'min': 100, 'time': 536}, {'max': 200, 'min': 150, 'time': 672}, {'max': 250, 'min': 200, 'time': 821}, {'max': 300, 'min': 250, 'time': 529}, {'max': 350, 'min': 300, 'time': 251}, {'max': 400, 'min': 350, …
```
> Add get_athlete_zone method on client

- .all-contributorsrc
- README.md
I have setup the all contributors bot to run on stravalib. This pr adds the necessary config needed for the bot to run.  
This pr includes a config file and an updated readme that carves out space for the bot to add new contributors. 
I didn't update the changelog for this pr. it won't impact the code.
> feat(bot): setup all contributors bot in stravalib

- .pre-commit-config.yaml
- examples/strava-oauth/server.py
This is manually updated precommit - we can close #590 
i don't think this warrants a changelog!
> chore: update precommit config

- changelog.md
closes #599  This is release 2.1.0 as discussed in slack!
> Release: v2.1.0

- changelog.md
This is just a small update to the changelog after seeing what the generated release notes looked like.
> Fix: update changelog notes

- .github/dependabot.yml
I'm just getting this up because our actions keep getting out of date. so this will make those node deprecation warnings go away as it updates things for us.
> Add: dependabot to update actions

- .github/dependabot.yml
- .github/workflows/build-test.yml
- changelog.md
- src/stravalib/client.py
- src/stravalib/tests/conftest.py
- src/stravalib/tests/integration/test_client.py
closes #321
This pr fixes the segment_efforts api endpoint. I'm struggling a lot with understanding what is broken in the tests and would appreciate any input! This is why I created #603 as I think i generally understand the mock behavior but i clearly don't understand how to use it as these tests don't work as expected. 
> fix(endpoint): Update segment_efforts endpoint to match the currently documented endpoint

- changelog.md
- docs/conf.py
- docs/contributing/development-guide.md
- docs/get-started/athletes.md
- docs/get-started/authenticate-with-strava.md
- noxfile.py
- src/stravalib/tests/integration/strava_api_stub.py
- src/stravalib/tests/integration/test_client.py
closes #292
I've been fighting a bit with the test suite and so I took some time to better understand our mock setup.
This PR should close the existing issue around documenting the mock. 
I could also add some examples of using it if that would be useful? 
I added some text around how the mock works. 
> feat(docs): add specifics about using our mock fixture

- CONTRIBUTING.md
- README.md
- changelog.md
- docs/get-started/activities.md
There is no open issue for this but I noticed some overlap in our dev docs/readme / contributing guide. 
Because of that it's easy for information to get out of sync. I've fixed this in this PR but adding LINKS to docs in our readme and contributing guides.  
Hopefully things won't get as out of sync that way! 
> doc: update docs so information is in one place

- changelog.md
* [An overview of our release workflow can be found in our documentation.](https://stravalib.readthedocs.io/en/latest/contributing/build-release-guide.html)
* [Before making a release be sure to check out test PyPI](https://test.pypi.org/project/stravalib/) to ensure that the build is working properly.
> :sparkles: Release 2.2

- .github/workflows/publish-pypi.yml
- README.md
- changelog.md
- docs/get-started/authenticate-with-strava.md
closes #622
This is a small update to our auth get started page. It adds information on using the auto refresh feature 🚀 
I also noticed our readme said we still support Python 3.9 so I updated that as well 🙈 
> Add: documentation on auto refresh

- .github/workflows/build-test.yml
- changelog.md
- docs/conf.py
- noxfile.py
- pyproject.toml
- src/stravalib/client.py
- src/stravalib/model.py
- src/stravalib/protocol.py
- src/stravalib/tests/auth_responder.py
- src/stravalib/tests/integration/strava_api_stub.py
- src/stravalib/tests/integration/test_client.py
- src/stravalib/tests/unit/test_model.py
- src/stravalib/util/limiter.py
Python 3.13 was released in October 2024, let's test it on CI and add the Trove clasifier.
I also ran the [Ruff pyupgrade (UP) rules](https://docs.astral.sh/ruff/rules/#pyupgrade-up) to upgrade the Python syntax -- it's mostly f-strings and type annotations. This rule could also be added to `pyproject.toml`.
_If you are having a hard time getting the tests to run correctly feel free to
ping one of the maintainers here!_
> Add support for Python 3.13

- changelog.md
* [An overview of our release workflow can be found in our documentation.](https://stravalib.readthedocs.io/en/latest/contributing/build-release-guide.html)
* [Before making a release be sure to check out test PyPI](https://test.pypi.org/project/stravalib/) to ensure that the build is working properly.
> :sparkles: Release 2.3 :rocket:

- README.md
- src/stravalib/protocol.py
closes #issue-this-closes-here
- This PR fix the broken link to the tutorial “How to refresh and auto refresh your app token using stravalib” on README
_If you are having a hard time getting the tests to run correctly feel free to
ping one of the maintainers here!_
> Fix: Update broken link How to refresh and auto refresh... on README

- changelog.md
- docs/conf.py
closes #640 
Change the announcement href link to 
```
/en/latest/whats-new/stravalib-2.html
```
The current link `whats-new/stravalib-2.html` does not work properly against any other page unless its in the main page: `https://stravalib.readthedocs.io/en/latest/`
When you click the link on the main homepage, `https://stravalib.readthedocs.io/en/latest/` it leads to 
```
https://stravalib.readthedocs.io/en/latest/whats-new/stravalib-2.html
```
When you clink the link on any other page, for example: `https://stravalib.readthedocs.io/foo/bar`.
It leads to
```
https://stravalib.readthedocs.io/foo/bar/whats-new/stravalib-2.html
```
which is incorrect and leads to **404: Not Found**
Select the statement best describes …
> Doc: fix stravalib 2.x announcement link

- changelog.md
- src/stravalib/tests/unit/test_limiter.py
- src/stravalib/util/limiter.py
closes #663 
A change is made to `casefold()` the keys in the header `dict` in the `get_rates_from_response_headers` function. This ensures that header fields are compared with case-insensitivity as required in the [HTTP/2 spec](https://httpwg.org/specs/rfc7540.html#HttpHeaders). It also updates the limiter tests to use a response header with lowercase fields to properly emulate an up-to-date response header from the Strava API.
_If you are having a hard time getting the tests to run correctly feel free to
ping one of …
> FIX: Casefold Response Headers
